Re-add new E2E tests

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -251,6 +251,99 @@ workflows:
         - android_additional_params: ''
         - cache_level: all
 
+  test_additional_build_params_android:
+    before_run:
+    - _expose_xcode_version
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -eo pipefail
+
+            if [[ ${XCODE_MAJOR_VERSION} -lt 11 ]]; then
+              echo "This test case requires Xcode >= 11, skipping..."
+              exit 0
+            fi
+
+            envman add --key XCODE_MAJOR_VERSION_AT_LEAST_11 --value "true"
+    - bitrise-run:
+        run_if: '{{enveq "XCODE_MAJOR_VERSION_AT_LEAST_11" "true"}}'
+        inputs:
+        - workflow_id: utility_test_additional_build_params_android
+        - bitrise_config_path: ./e2e/bitrise.yml
+
+  utility_test_additional_build_params_android:
+    before_run:
+    - _clear_workdir
+    steps:
+    - git::https://github.com/bitrise-steplib/bitrise-step-simple-git-clone.git:
+        inputs:
+        - repository_url: $SAMPLE_APP_URL
+        - clone_into_dir: ./
+        - branch: master
+    - path::./:
+        inputs:
+        - additional_build_params: "--split-per-abi"
+        - platform: android
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -eo pipefail
+            apk_count=$(echo $BITRISE_APK_PATH_LIST | sed 's/|/\n/g' | wc -w)
+            if [ $apk_count -eq 1 ]; then
+              echo "Got 1 exported APK but more were expected because --split-per-abi was specified."
+              exit 1
+            fi
+
+  test_additional_build_params_ios:
+    before_run:
+    - _expose_xcode_version
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -eo pipefail
+
+            if [[ ${XCODE_MAJOR_VERSION} -lt 11 ]]; then
+              echo "This test case requires Xcode >= 11, skipping..."
+              exit 0
+            fi
+
+            envman add --key XCODE_MAJOR_VERSION_AT_LEAST_11 --value "true"
+    - bitrise-run:
+        run_if: '{{enveq "XCODE_MAJOR_VERSION_AT_LEAST_11" "true"}}'
+        inputs:
+        - workflow_id: utility_test_additional_build_params_ios
+        - bitrise_config_path: ./e2e/bitrise.yml
+
+  utility_test_additional_build_params_ios:
+    before_run:
+    - _clear_workdir
+    steps:
+    - git::https://github.com/bitrise-steplib/bitrise-step-simple-git-clone.git:
+        inputs:
+        - repository_url: $SAMPLE_APP_URL
+        - clone_into_dir: ./
+        - branch: master
+    - path::./:
+        inputs:
+        - additional_build_params: "--build-number 123456789"
+        - platform: ios
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -eo pipefail
+            plutil -convert xml1 $BITRISE_APP_DIR_PATH/Info.plist
+            grep -e "123456789" $BITRISE_APP_DIR_PATH/Info.plist
+            if [ $? -eq 1 ]; then
+              echo "Build number 123456789 was not found in Info.plist."
+              exit 1
+            fi
+
   _expose_xcode_version:
     steps:
     - script:
